name: R Script Execution

on:
  schedule:
    - cron: '25 1 * * *'  # Exécute le workflow tous les jours à 01:25 UTC

jobs:
  run-r-script:
    runs-on: ubuntu-latest

    steps:
    - name: Vérifier le code
      uses: actions/checkout@v2

    - name: Installer R
      uses: r-lib/actions/setup-r@v2

    - name: Installer les dépendances
      run: |
        Rscript -e 'install.packages(c("dplyr", "ggplot2"))'  # Ajoute les packages nécessaires

    - name: Exécuter le script R
      run: |
        app_initial_test.R  # Remplace par le nom de ton script

    - name: Ajouter et pousser les résultats
      run: |
        git config --local user.email "romu.zami@gmail.com"
        git config --local user.name "Romu"
        git add .
        git commit -m "Mise à jour des résultats" || echo "Aucun changement à pousser"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
